### ISSUE TITLE
[Feature request] Unique rover colours

### ISSUE THREAD

**Issue by OmarAlashqar** [wahidshafique/mars-rover-svelte#1]
Love the effort you've put in so far! We've been using this tool internally for high value projects and have found it extremely useful in simulating robotics on extraterrestrial terrain.

With that said, we've recently realized that this is utterly unusable in the current state since we have multiple rovers stationed on an extraterrestrial planet whose name is classified. This simulation currently only supports one color for the rover, which means that our sub-par machine learning model can't tell the rovers apart.

Our dedicated staff engineers were not able to fork this project and fix this issue, so we're reaching out as a final resort hoping that you'd be able to fix it for us! 🔧 ❤️

**Comment by wahidshafique** [comment]
@OmarAlashqar  Hey Omar! Thank you for notifying our dedicated engineering department about this oversight. We never factored in the need for various tints and I've elevated this issue to our triage pipeline squads. As per our fuzzy QFD process (described in ISO 16355-1:2015), you should expect a fix sometime in Q1, once we've cleared it with our product and senior rover development teams. Happy roving!

**Comment by wahidshafique** [comment]
Done!
